# Generated by Django 5.1.7 on 2025-08-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_ingredient_comment_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='request_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='request_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='request_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
